### ISSUE TITLE
Can't declare column attributes like in 6.x service implementation

### ISSUE THREAD

**Issue by rockypra** [yajra/laravel-datatables-buttons#19]
### Summary of problem or feature request
There is a breaking changes when I'm trying to derivate a Laravel Datatable 6.x service pattern from an old project to a new project that is using Laravel 5.4 and Laravel Datatable 7.x . 
I'm having this problem since Laravel Datatable 7.x service implementation are separated into this plugin.
Declaring column like this would run just fine in Laravel 5.3 with Laravel Datatable version 6.x, but it seems broken on the Laravel 5.4 with Laravel Datatable 7.x.
```php
    protected function getColumns()
    {
        return [
            'id' => [ 'title' => '#' ],
            'name' => [ 'title' => 'Nama Produk' ],
            'description' => [ 'title' => 'Deskripsi' ],
            'image' => [ 'title' => 'Gambar' ],
            'created_at' => [ 'title' => 'Dibuat' ],
            'updated_at' => [ 'title' => 'Diperbarui' ],
        ];
    }
```
I must use array of column name in `getColumns` and in order to get it working again like this
```php
    protected function getColumns()
    {
        return [
            'id',
            'name',
            'description',
            'image',
            'created_at',
            'updated_at'
        ];
    }
```
I'm following this HTML Builder example (http://yajrabox.com/docs/laravel-datatables/7.0/html-builder-table) and modify them accordingly but it still throws the error like in the stack trace below.
There is a workaround though I wish I could declare the columns attributes like in the 6.x.

### Stack trace
```
[2017-05-07 12:59:53] local.ERROR: exception 'ErrorException' with message 'strtolower() expects parameter 1 to be string, array given' in E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Database\Grammar.php:58
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'strtolower() ex...', 'E:\\Dev\\crm_neng...', 58, Array)
#1 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Database\Grammar.php(58): strtolower(Array)
#2 [internal function]: Illuminate\Database\Grammar->wrap(Array)
#3 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Database\Grammar.php(126): array_map(Array, Array)
#4 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Database\Query\Grammars\Grammar.php(131): Illuminate\Database\Grammar->columnize(Array)
#5 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Database\Query\Grammars\Grammar.php(85): Illuminate\Database\Query\Grammars\Grammar->compileColumns(Object(Illuminate\Database\Query\Builder), Array)
#6 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Database\Query\Grammars\Grammar.php(60): Illuminate\Database\Query\Grammars\Grammar->compileComponents(Object(Illuminate\Database\Query\Builder))
#7 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Database\Query\Grammars\MySqlGrammar.php(38): Illuminate\Database\Query\Grammars\Grammar->compileSelect(Object(Illuminate\Database\Query\Builder))
#8 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1652): Illuminate\Database\Query\Grammars\MySqlGrammar->compileSelect(Object(Illuminate\Database\Query\Builder))
#9 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(1236): Illuminate\Database\Query\Builder->toSql()
#10 E:\Dev\crm_nengs\vendor\yajra\laravel-datatables-oracle\src\Engines\EloquentEngine.php(56): Illuminate\Database\Eloquent\Builder->__call('toSql', Array)
#11 E:\Dev\crm_nengs\vendor\yajra\laravel-datatables-oracle\src\Engines\EloquentEngine.php(56): Illuminate\Database\Eloquent\Builder->toSql()
#12 E:\Dev\crm_nengs\vendor\yajra\laravel-datatables-oracle\src\Engines\QueryBuilderEngine.php(89): Yajra\Datatables\Engines\EloquentEngine->count()
#13 E:\Dev\crm_nengs\vendor\yajra\laravel-datatables-oracle\src\Engines\BaseEngine.php(499): Yajra\Datatables\Engines\QueryBuilderEngine->totalCount()
#14 E:\Dev\crm_nengs\vendor\yajra\laravel-datatables-oracle\src\Engines\QueryBuilderEngine.php(79): Yajra\Datatables\Engines\BaseEngine->make(true, false)
#15 E:\Dev\crm_nengs\vendor\yajra\laravel-datatables-buttons\src\Services\DataTable.php(173): Yajra\Datatables\Engines\QueryBuilderEngine->make(true)
#16 E:\Dev\crm_nengs\vendor\yajra\laravel-datatables-buttons\src\Services\DataTable.php(136): Yajra\Datatables\Services\DataTable->ajax()
#17 E:\Dev\crm_nengs\app\Http\Controllers\ProductController.php(21): Yajra\Datatables\Services\DataTable->render('admin.products....', Array)
#18 [internal function]: App\Http\Controllers\ProductController->index(Object(App\DataTables\ProductsDataTable))
#19 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(55): call_user_func_array(Array, Array)
#20 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('index', Array)
#21 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Route.php(204): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\ProductController), 'index')
#22 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Route.php(160): Illuminate\Routing\Route->runController()
#23 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(559): Illuminate\Routing\Route->run()
#24 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 E:\Dev\crm_nengs\vendor\santigarcor\laratrust\src\Laratrust\Middleware\LaratrustRole.php(54): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Laratrust\Middleware\LaratrustRole->handle(Object(Illuminate\Http\Request), Object(Closure), 'admin')
#27 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(561): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(520): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#52 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(498): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#53 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(174): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#54 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#55 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#65 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#66 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#68 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#69 E:\Dev\crm_nengs\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#70 E:\Dev\crm_nengs\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#71 {main} 
```

### System details
- Operating System: Windows 10 Pro 64-bit
- PHP Version: 5.6.24
- Laravel Version: 5.4.19
- Laravel-Datatables Version:  7.3.0

**Comment by cre8** [comment]
in 7.x you can pass a 2d array:

```
protected function getColumns()
    {
        return [
            [
                'name' => 'id',
                'data' => 'id',
               'title' => 'Awesome ID'
            ],
            ....
        ];
    }
```

**Comment by rockypra** [comment]
Well, thank you for the heads up. These breaking changes should be noted in the upgrade guides.

**Comment by yajra** [comment]
@rockypra are you sure it's not working? There are no breaking changes like this afaik. I am using the same array structure on projects.

**Comment by yajra** [comment]
@cre8 thanks for the reply but the same is true for v6.x

**Comment by julianovmartins** [comment]
change:
```php
    public function query()
    {
        $query = Pessoa::query()->select($this->getColumns());

        return $this->applyScopes($query);
    }
```
to
```php
public function query()
    {
        $query = Pessoa::query();

        return $this->applyScopes($query);
    }
```

**Comment by royduin** [comment]
Same issue here...

**Comment by Albvadi** [comment]
Same issue. Posted [here too](https://github.com/yajra/laravel-datatables/issues/1519)

**Comment by yajra** [comment]
Same solution / concept posted on #1519 will resolve this issue. Thanks!
